
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cluster.k8s.ianvs.cloud
  resources:
  - credentials
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.k8s.ianvs.cloud
  resources:
  - credentials/finalizers
  verbs:
  - update
- apiGroups:
  - cluster.k8s.ianvs.cloud
  resources:
  - credentials/status
  verbs:
  - get
  - patch
  - update
